#ifndef ADPCMCOEFFS_HPP
#define ADPCMCOEFFS_HPP
/*
================= DO NOT EDIT THIS FILE ====================
This file has  been automatically generated by genstructs.py

Please  edit  structs.xml instead, and  re-run genstructs.py
============================================================
*/
#include "StructLoader.hpp"
struct AdpcmCoeffs {
  std::int16_t iCoef1;
  std::int16_t iCoef2;
};

template <> struct StructLoader<AdpcmCoeffs> {
  static const char* readBuffer(const char *begin, const char *end, AdpcmCoeffs &output) {
    if (begin > end) {
      throw DLSynth::Error("Wrong data size", DLSynth::ErrorCode::INVALID_FILE);
    }
    const char *cur_pos = begin;
    cur_pos = StructLoader<std::int16_t>::readBuffer(cur_pos, end, output.iCoef1);
    cur_pos = StructLoader<std::int16_t>::readBuffer(cur_pos, end, output.iCoef2);
    return cur_pos;
  }
};
#endif
