#ifndef INSH_HPP
#define INSH_HPP
/*
================= DO NOT EDIT THIS FILE ====================
This file has  been automatically generated by genstructs.py

Please  edit  structs.xml instead, and  re-run genstructs.py
============================================================
*/
#include "StructLoader.hpp"
struct insh {
  std::uint32_t cRegions;
  std::uint32_t ulBank;
  std::uint32_t ulInstrument;
};

template <> struct StructLoader<insh> {
  static const char* readBuffer(const char *begin, const char *end, insh &output) {
    if (begin > end) {
      throw DLSynth::Error("Wrong data size", DLSynth::ErrorCode::INVALID_FILE);
    }
    const char *cur_pos = begin;
    cur_pos = StructLoader<std::uint32_t>::readBuffer(cur_pos, end, output.cRegions);
    cur_pos = StructLoader<std::uint32_t>::readBuffer(cur_pos, end, output.ulBank);
    cur_pos = StructLoader<std::uint32_t>::readBuffer(cur_pos, end, output.ulInstrument);
    return cur_pos;
  }
};
#endif
