STRUCT_BEGIN(WaveFormat)
FIELD(std::uint16_t, FormatTag)
FIELD(std::uint16_t, NumChannels)
FIELD(std::uint32_t, SamplesPerSec)
FIELD(std::uint32_t, AvgBytesPerSec)
FIELD(std::uint16_t, BlockAlign)

STRUCT_METHOD(static constexpr std::uint16_t Unknown = 0x0000;)
STRUCT_METHOD(static constexpr std::uint16_t Pcm = 0x0001;)
STRUCT_METHOD(static constexpr std::uint16_t MsAdpcm = 0x0002;)
STRUCT_METHOD(static constexpr std::uint16_t Float = 0x0003;)
STRUCT_METHOD(static constexpr std::uint16_t ALaw = 0x0006;)
STRUCT_METHOD(static constexpr std::uint16_t MuLaw = 0x0007;)
STRUCT_METHOD(static constexpr std::uint16_t DviAdpcm = 0x0011;)
STRUCT_METHOD(static constexpr std::uint16_t ImaAdpcm = DviAdpcm;)
STRUCT_END(WaveFormat)