#ifndef WLNK_HPP
#define WLNK_HPP
/*
================= DO NOT EDIT THIS FILE ====================
This file has  been automatically generated by genstructs.py

Please  edit  structs.xml instead, and  re-run genstructs.py
============================================================
*/
#include "StructLoader.hpp"
struct wlnk {
  std::uint16_t fusOptions;
  std::uint16_t usPhaseGroup;
  std::uint32_t ulChannel;
  std::uint32_t ulTableIndex;
};

template <> struct StructLoader<wlnk> {
  static const char* readBuffer(const char *begin, const char *end, wlnk &output) {
    if (begin > end) {
      throw DLSynth::Error("Wrong data size", DLSynth::ErrorCode::INVALID_FILE);
    }
    const char *cur_pos = begin;
    cur_pos = StructLoader<std::uint16_t>::readBuffer(cur_pos, end, output.fusOptions);
    cur_pos = StructLoader<std::uint16_t>::readBuffer(cur_pos, end, output.usPhaseGroup);
    cur_pos = StructLoader<std::uint32_t>::readBuffer(cur_pos, end, output.ulChannel);
    cur_pos = StructLoader<std::uint32_t>::readBuffer(cur_pos, end, output.ulTableIndex);
    return cur_pos;
  }
};
#endif
