#ifndef WSMP_LOOP_HPP
#define WSMP_LOOP_HPP
/*
================= DO NOT EDIT THIS FILE ====================
This file has  been automatically generated by genstructs.py

Please  edit  structs.xml instead, and  re-run genstructs.py
============================================================
*/
#include "StructLoader.hpp"
struct wsmp_loop {
  std::uint32_t cbSize;
  std::uint32_t ulLoopType;
  std::uint32_t ulLoopStart;
  std::uint32_t ulLoopLength;
};

template <> struct StructLoader<wsmp_loop> {
  static const char* readBuffer(const char *begin, const char *end, wsmp_loop &output) {
    if (begin > end) {
      throw DLSynth::Error("Wrong data size", DLSynth::ErrorCode::INVALID_FILE);
    }
    const char *cur_pos = begin;
    cur_pos = StructLoader<std::uint32_t>::readBuffer(cur_pos, end, output.cbSize);
    cur_pos = StructLoader<std::uint32_t>::readBuffer(cur_pos, end, output.ulLoopType);
    cur_pos = StructLoader<std::uint32_t>::readBuffer(cur_pos, end, output.ulLoopStart);
    cur_pos = StructLoader<std::uint32_t>::readBuffer(cur_pos, end, output.ulLoopLength);
    return cur_pos;
  }
};
#endif
